name: Go
on: [push]
jobs:

  build:
    name: Build&test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...
